### PR TITLE
Claim modal working, other modal refactor

### PR DESCRIPTION
**Pull request by shafu0x**

### CODE REVIEW

**Comment by shafu0x** [comment]
@sdkayy great job on your first PR!

A couple of points:
1) lets remove Activation.jsx for this pr
2) you created `StatPair`component, is it possible to re-use `PopupTable` `PopupTableRow` system like the one in `Deposit.jsx`?
3) is the `claim` functionality actually working?

**Comment by sdkayy** [comment]
> * lets remove Activation.jsx for this pr

 I kinda added more to this already and just wanna get the activation modal working now too really fast and just wait for the toggle action? 
> * you created `StatPair`component, is it possible to re-use `PopupTable` `PopupTableRow` system like the one in `Deposit.jsx`?

 Yes will do!
> * is the `claim` functionality actually working?

Yes. With the most active claim window I was able to claim. https://goerli.etherscan.io/tx/0x211a3b49f91cd49195d86f8bd5e664c64e10b64529cb13c0e4d00328959581f0

**Comment by shafu0x** [comment]
1) I see, lets remove it for now. I have no clue how kores is going to design that so maybe it will not be a modal.
2) Cool, refactor it and I think this PR is ready to be merged in
3) thats awesome!

**Comment by shafu0x** [comment]
@sdkayy and lets put the claim button under the deposit amount.

**Pull request merged**
